name: jax
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python
  - jax
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pytest
  - tqdm
  - ipython
  - ase
  - scikit-learn
  - pip:
    - optax
    - jaxopt
